name: Update Pinokio Site
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  update_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pinokio fetch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/pinokio_fetch.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add site/
          git commit -m "Update Pinokio site" || echo "No changes"
          git push
