name: Update Pinokio Data

on:
  schedule:
    - cron: "0 6 * * 0"   # every Sunday at 06:00 UTC
  workflow_dispatch:       # allow manual trigger
  push:
    paths:
      - "pinokio_scraper.py"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload-artifact.outputs.artifact-name }}
   steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      env:
        GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}
      run: python pinokio_scraper.py
      
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

