name: Update Pinokio Data

on:
  schedule:
    - cron: "0 6 * * 0"   # every Sunday at 06:00 UTC
  workflow_dispatch:
  push:
    paths:
      - "pinokio_scraper_2.py"
      - "requirements.txt"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: cache the sqlite DB so we don't re-hit upstreams unnecessarily
      - name: Cache DB
        uses: actions/cache@v4
        with:
          path: pinokio.db
          key: pinokio-db-${{ github.run_id }}
          restore-keys: |
            pinokio-db-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run scraper (migrate + backfill)
        env:
          GH_TOKEN: ${{ secrets.MY_GH_TOKEN }}
          PINOKIO_ORG: pinokiofactory
          REFRESH: "1"                   # <-- first run only
          DB_FILE: "pinokio.db"
          CSV_FILE: "pinokio_repos.csv"
          XLSX_FILE: "pinokio_repos.xlsx"
          JSON_FILE: "docs/data.json"
        run: |
          python pinokio_scraper_2.py

      - name: Upload artifacts (csv/xlsx/json/db)
        uses: actions/upload-artifact@v4
        with:
          name: pinokio-data
          path: |
            pinokio_repos.csv
            pinokio_repos.xlsx
            docs/data.json
            pinokio.db

      - name: Publish outputs (including DB) to repo
        run: |
          mkdir -p docs
          cp pinokio.db docs/pinokio.db
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data.json docs/pinokio.db pinokio_repos.csv pinokio_repos.xlsx || true
          if git diff --cached --quiet; then
            echo "No changes to outputs, skipping commit."
          else
            git commit -m "Update data + DB [skip ci]"
            git push
          fi
